### ISSUE TITLE
QX backend fails on qiskit circuit

### ISSUE THREAD

**Issue by peendebak** [QuTech-Delft/quantuminspire#100] opened 2021-05-28 13:30 UTC
# Bug report

## What did you try to do?

Running a trivial qiskit circuit fails on the QX backend.

A minimal example:
```
from qiskit.circuit import QuantumCircuit
from qiskit import execute

from quantuminspire.credentials import load_account
from quantuminspire.qiskit import QI
authentication = get_token_authentication(load_account())
qi_api = QuantumInspireAPI(authentication=authentication)
QI.set_authentication(authentication)

qi_backend = QI.get_backend("QX single-node simulator")

qc=QuantumCircuit(2)
qc.draw()

qi_job = execute(qc, backend=qi_backend, shots=100)
result = qi_job.result()
```

## What did you expect to happen?

The circuit should be executed.

## What actually happened?

An error is generated: `QisKitBackendError: Invalid amount of classical bits (0)!`.
This should not happen since the circuit does not involve any conditional gates, so classical bits are not required.
## Environment

Please specify:
* operating system, version and distribution: Windows 10
* python version (`python --version`) and distribution: 3.8

**Comment by kel85uk** [comment] 2021-05-28 13:43
With Qiskit, you always need to specify the same number of classical registers. I would modify your test case with this:
```
qr = QuantumRegister(2, 'x')
cr = ClassicalRegister(2, 'c')
qc = QuantumCircuit(qr, cr)
```

**Comment by QFer** [comment] 2021-06-01 15:19
@peendebak You are right, for Qiskit this is not required, but the purpose of using the SDK's Qiskit backend is to run Qiskit algorithms on a backend that accepts valid cQASM. Because cQASM 1.0 has the same number of classical registers as qubits by design SDK does a simple check for the number of classical bits before sending the experiment to the backend.

The first circuit cannot be translated to valid cQASM because there are no classical bits defined at all. The error QisKitBackendError: Invalid amount of classical bits (0) is right. In the backend the 2 qubits you defined are measured and implicitly 'stored' in the equivalent classical registers. Because there are none defined you get this error.

The same accounts for the second algorithm but here you have defined 1 classical bit. Because this could be a valid cQASM algorithm when you measure both qubits to the single classical bit defined yourself.
```
qc=QuantumCircuit(2,1)
qc.draw()
qc.measure(0, 0)
qc.measure(1, 0)
```
Because you don't measure at all, in the backend the 2 qubits you defined are measured and implicitly 'stored' in the equivalent classical registers, which results in an error because there is only one defined. To generate this error upfront we have to parse the algorithm for all situations. This can become quit complex. We have chosen not to do that.

When binary controlled gates are used and the number of classical registers is greater than the number of qubits an error is raised because otherwise we can get something like:
```
                q = QuantumRegister(2)
                c = ClassicalRegister(4)
                circuit = QuantumCircuit(q, c)
                circuit.h(q[0]).c_if(c, 15)
```
which again is impossible in cQASM but perfectly valid in Qiskit.

**Comment by eendebakpt** [comment] 2021-06-03 10:54
@QFer Although I think the first example should be handles by QI, the error message is valid and allows a user to modify the algorithm so that it can be submitted. 
The second example results in a successful execution of the algorithm, but an error in the post-processing:
```

  File "c:\projects\py38\lib\site-packages\quantuminspire\qiskit\backend_qx.py", line 376, in __qubit_to_classical_hex
    classical_state[c] = qubit_state[q]

IndexError: list assignment index out of range
```
Either the post-processing should be updated to handle this case, or in the pre-processing a proper error message should be generated. This error message does not help a user to figure out what is the problem.

**Comment by QFer** [comment] 2021-06-03 11:10
@peendebak I agree, On second thoughts I think we can fix it in the pre-processing and show a more helpful message.

**Comment by QFer** [comment] 2021-06-11 12:40
@peendebak fixed in https://github.com/QuTech-Delft/quantuminspire/pull/102

**Closed** 2021-07-02 08:09 UTC
